// All admin panel text, in Albanian (the client's language). Option labels (types, statuses,
// features) come from the site's Albanian dictionary so both always match.
import sq from "@/i18n/dictionaries/sq.json";
import { zones } from "@/data/properties";

export const a = {
  panel: "Paneli i administrimit",
  nav: { properties: "Pronat", viewSite: "Shiko faqen", logout: "Dil", signedInAs: "I kyçur si" },
  login: {
    title: "Hyr në panel",
    username: "Emri i përdoruesit",
    password: "Fjalëkalimi",
    submit: "Hyr",
    submitting: "Duke hyrë…",
    invalid: "Emri i përdoruesit ose fjalëkalimi është i gabuar.",
    rateLimited: "Shumë përpjekje. Provoni përsëri pas disa minutash.",
    expired: "Seanca ka skaduar. Hyni përsëri.",
  },
  list: {
    title: "Pronat",
    add: "Shto pronë",
    search: "Kërko sipas referencës ose emrit",
    searchButton: "Kërko",
    clearSearch: "Pastro",
    total: "{total} prona",
    empty: "Nuk ka ende prona. Shtoni të parën.",
    noResults: "Asnjë pronë nuk u gjet.",
    photo: "Foto",
    listing: "Prona",
    price: "Çmimi",
    visibility: "Dukshmëria",
    updated: "Përditësuar",
    published: "Publikuar",
    hidden: "E fshehur",
    featured: "E veçantë",
    edit: "Ndrysho",
    view: "Shiko në faqe",
    page: "Faqja {page} nga {pages}",
    previous: "Mëparshme",
    next: "Tjetra",
  },
  form: {
    newTitle: "Pronë e re",
    editTitle: "Ndrysho pronën",
    back: "Kthehu te pronat",
    content: "Përmbajtja",
    contentHint: "Titulli kërkohet në të tri gjuhët.",
    languages: { sq: "Shqip", en: "English", de: "Deutsch" },
    title: "Titulli",
    description: "Përshkrimi",
    details: "Të dhënat",
    zone: "Zona",
    type: "Lloji",
    status: "Statusi",
    area: "Sipërfaqja (m²)",
    price: "Çmimi (€)",
    priceOnRequest: "Çmimi me kërkesë",
    municipality: "Komuna",
    feature: "Cilësi shtesë",
    location: "Vendndodhja",
    locationHint: "Klikoni në hartë ose tërhiqni shënjuesin për të vendosur vendndodhjen.",
    lat: "Gjerësia gjeografike",
    lng: "Gjatësia gjeografike",
    mapLabel: "Harta për zgjedhjen e vendndodhjes",
    mapLoading: "Harta po ngarkohet…",
    visibility: "Dukshmëria",
    published: "Publikuar në faqe",
    publishedHint: "Kur është e fikur, prona nuk shfaqet në faqe.",
    featured: "Pronë e veçantë",
    featuredHint: "Shfaqet te “Pronat e veçanta” në faqen kryesore.",
    create: "Krijo pronën",
    save: "Ruaj ndryshimet",
    saving: "Duke ruajtur…",
    saved: "Ndryshimet u ruajtën.",
    created: "Prona u krijua. Tani mund të shtoni fotot.",
    invalid: "Kontrolloni fushat e shënuara.",
    error: "Nuk u ruajt. Provoni përsëri.",
    reference: "Referenca",
    publicLink: "Shiko në faqe",
    leaveTitle: "Të largoheni pa ruajtur?",
    leaveText: "Keni ndryshime që nuk janë ruajtur. Nëse largoheni, ato humbasin.",
    leaveConfirm: "Largohu pa ruajtur",
  },
  images: {
    title: "Fotot",
    hint: "JPEG, PNG ose WebP. Fotot e mëdha zvogëlohen automatikisht para ngarkimit. Foto e parë është foto kryesore.",
    add: "Shto foto",
    uploading: "Duke ngarkuar {n} nga {total}…",
    empty: "Nuk ka ende foto. Pa foto, në faqe shfaqet një kuti gri.",
    cover: "Kryesore",
    photo: "Foto {n}",
    moveLeft: "Lëviz majtas",
    moveRight: "Lëviz djathtas",
    delete: "Fshi foton",
    deleteTitle: "Të fshihet kjo foto?",
    deleteText: "Foto fshihet përgjithmonë.",
    failed: "{name}: nuk u ngarkua ({reason}).",
    tooMany: "Një pronë mund të ketë deri në 30 foto.",
    error: "Veprimi nuk u krye. Provoni përsëri.",
  },
  delete: {
    button: "Fshi pronën",
    title: "Të fshihet kjo pronë?",
    text: "Prona, përkthimet dhe të gjitha fotot e saj fshihen përgjithmonë. Ky veprim nuk kthehet.",
    confirm: "Po, fshije",
    cancel: "Anulo",
    deleting: "Duke fshirë…",
    error: "Prona nuk u fshi. Provoni përsëri.",
  },
  options: {
    zones: zones.map((z) => ({ value: z.slug, label: z.name.sq })),
    types: sq.propertyTypes,
    statuses: sq.propertyStatus,
    features: sq.propertyFeatures,
  },
};

export const fill = (template: string, values: Record<string, string | number>) =>
  template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
